/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule

module DIG_D_FF_Nbit
#(
    parameter Bits = 2,
    parameter Default = 0
)
(
   input [(Bits-1):0] D,
   input C,
   output [(Bits-1):0] Q,
   output [(Bits-1):0] \~Q
);
    reg [(Bits-1):0] state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module Mux_4x1_NBits #(
    parameter Bits = 2
)
(
    input [1:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module fourbitadder (
  input C_input,
  input A0,
  input B0,
  input A1,
  input A2,
  input A3,
  input B1,
  input B2,
  input B3,
  output Cout,
  output S0,
  output S1,
  output S2,
  output S3
);
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  assign s4 = (A0 ^ B0);
  assign s6 = (A1 ^ B1);
  assign s8 = (A2 ^ B2);
  assign s10 = (A3 ^ B3);
  assign S0 = (s4 ^ C_input);
  assign s5 = ((s4 & C_input) | (A0 & B0));
  assign S1 = (s6 ^ s5);
  assign s7 = ((s6 & s5) | (A1 & B1));
  assign S2 = (s8 ^ s7);
  assign s9 = ((s8 & s7) | (A2 & B2));
  assign S3 = (s10 ^ s9);
  assign Cout = ((s10 & s9) | (A3 & B3));
endmodule

module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module bcd_adder (
  input [3:0] NumberA,
  input [3:0] NumberB,
  input syc,
  input cin,
  output [3:0] N1,
  output coutt,
  output [3:0] N2
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire [3:0] s18;
  wire s19;
  assign s0 = NumberA[0];
  assign s2 = NumberA[1];
  assign s3 = NumberA[2];
  assign s4 = NumberA[3];
  assign s1 = NumberB[0];
  assign s5 = NumberB[1];
  assign s6 = NumberB[2];
  assign s7 = NumberB[3];
  fourbitadder fourbitadder_i0 (
    .C_input( cin ),
    .A0( s0 ),
    .B0( s1 ),
    .A1( s2 ),
    .A2( s3 ),
    .A3( s4 ),
    .B1( s5 ),
    .B2( s6 ),
    .B3( s7 ),
    .Cout( s8 ),
    .S0( s9 ),
    .S1( s10 ),
    .S2( s11 ),
    .S3( s12 )
  );
  assign s13 = ((s10 & s12) | (s11 & s12) | s8);
  assign s19 = (s8 | (s12 & (s10 | s11)));
  fourbitadder fourbitadder_i1 (
    .C_input( 1'b0 ),
    .A0( s9 ),
    .B0( 1'b0 ),
    .A1( s10 ),
    .A2( s11 ),
    .A3( s12 ),
    .B1( s13 ),
    .B2( s13 ),
    .B3( 1'b0 ),
    .S0( s14 ),
    .S1( s15 ),
    .S2( s16 ),
    .S3( s17 )
  );
  Mux_2x1 Mux_2x1_i2 (
    .sel( syc ),
    .in_0( cin ),
    .in_1( s19 ),
    .out( coutt )
  );
  assign s18[0] = s14;
  assign s18[1] = s15;
  assign s18[2] = s16;
  assign s18[3] = s17;
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i3 (
    .sel( syc ),
    .in_0( NumberA ),
    .in_1( s18 ),
    .out( N1 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i4 (
    .sel( syc ),
    .in_0( NumberB ),
    .in_1( s18 ),
    .out( N2 )
  );
endmodule

module calculator (
  input [3:0] DATA,
  input DA,
  input CLK,
  output [3:0] D0,
  output [3:0] D1,
  output [3:0] D2,
  output [3:0] D3,
  output [3:0] D4,
  output [3:0] D5,
  output [3:0] D6,
  output [3:0] D7
);
  wire [3:0] D0_temp;
  wire [3:0] D1_temp;
  wire [3:0] D2_temp;
  wire [3:0] D3_temp;
  wire [3:0] D4_temp;
  wire [3:0] D5_temp;
  wire [3:0] D6_temp;
  wire [3:0] D7_temp;
  wire [3:0] s0;
  wire [3:0] s1;
  wire [3:0] s2;
  wire [3:0] s3;
  wire [3:0] s4;
  wire [3:0] s5;
  wire [3:0] s6;
  wire [3:0] s7;
  wire [3:0] s8;
  wire [3:0] s9;
  wire [3:0] s10;
  wire [3:0] s11;
  wire [3:0] s12;
  wire [3:0] s13;
  wire [3:0] s14;
  wire [3:0] s15;
  wire [3:0] s16;
  wire [3:0] s17;
  wire [3:0] s18;
  wire [3:0] s19;
  wire [3:0] s20;
  wire [3:0] s21;
  wire [3:0] s22;
  wire [3:0] s23;
  wire [1:0] s24;
  wire [3:0] s25;
  wire [3:0] s26;
  wire [3:0] s27;
  wire [3:0] s28;
  wire [3:0] s29;
  wire [3:0] s30;
  wire [3:0] s31;
  wire [3:0] s32;
  wire [3:0] s33;
  wire [3:0] s34;
  wire [3:0] s35;
  wire s36;
  wire [3:0] s37;
  wire [3:0] s38;
  wire s39;
  wire s40;
  wire [3:0] s41;
  wire [3:0] s42;
  wire s43;
  wire s44;
  wire s45;
  wire s46;
  wire [3:0] s47;
  wire s48;
  wire [3:0] s49;
  wire s50;
  wire [3:0] s51;
  wire s52;
  wire [3:0] s53;
  wire s54;
  wire [3:0] s55;
  wire s56;
  wire [3:0] s57;
  wire s58;
  wire [3:0] s59;
  wire [3:0] s60;
  assign s36 = (DATA[3] & DATA[2] & DATA[1]);
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i0 (
    .D( DA ),
    .C( CLK ),
    .Q( s39 )
  );
  assign s43 = (DATA[0] & DATA[1] & DATA[2] & DATA[3]);
  assign s40 = (DA & ~ s39);
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( s43 ),
    .C( CLK ),
    .Q( s44 )
  );
  assign s24[0] = ((s40 & ~ s36) | (s40 & s36 & DATA[0]));
  assign s24[1] = (s40 & s36);
  assign s45 = (s24[0] & s24[1]);
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i2 (
    .D( s0 ),
    .C( CLK ),
    .Q( D0_temp )
  );
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i3 (
    .D( s1 ),
    .C( CLK ),
    .Q( D1_temp )
  );
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i4 (
    .D( s2 ),
    .C( CLK ),
    .Q( D2_temp )
  );
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i5 (
    .D( s3 ),
    .C( CLK ),
    .Q( D3_temp )
  );
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i6 (
    .D( s4 ),
    .C( CLK ),
    .Q( D4_temp )
  );
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i7 (
    .D( s5 ),
    .C( CLK ),
    .Q( D5_temp )
  );
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i8 (
    .D( s6 ),
    .C( CLK ),
    .Q( D6_temp )
  );
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i9 (
    .D( s7 ),
    .C( CLK ),
    .Q( s8 )
  );
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i10 (
    .D( s9 ),
    .C( CLK ),
    .Q( s10 )
  );
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i11 (
    .D( s11 ),
    .C( CLK ),
    .Q( s12 )
  );
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i12 (
    .D( s13 ),
    .C( CLK ),
    .Q( s14 )
  );
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i13 (
    .D( s15 ),
    .C( CLK ),
    .Q( s16 )
  );
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i14 (
    .D( s17 ),
    .C( CLK ),
    .Q( s18 )
  );
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i15 (
    .D( s19 ),
    .C( CLK ),
    .Q( s20 )
  );
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i16 (
    .D( s21 ),
    .C( CLK ),
    .Q( D7_temp )
  );
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i17 (
    .D( s22 ),
    .C( CLK ),
    .Q( s23 )
  );
  Mux_4x1_NBits #(
    .Bits(4)
  )
  Mux_4x1_NBits_i18 (
    .sel( s24 ),
    .in_0( D0_temp ),
    .in_1( DATA ),
    .in_2( 4'b0 ),
    .in_3( s25 ),
    .out( s0 )
  );
  Mux_4x1_NBits #(
    .Bits(4)
  )
  Mux_4x1_NBits_i19 (
    .sel( s24 ),
    .in_0( D1_temp ),
    .in_1( s26 ),
    .in_2( 4'b0 ),
    .in_3( s27 ),
    .out( s1 )
  );
  Mux_4x1_NBits #(
    .Bits(4)
  )
  Mux_4x1_NBits_i20 (
    .sel( s24 ),
    .in_0( D2_temp ),
    .in_1( s28 ),
    .in_2( 4'b0 ),
    .in_3( s29 ),
    .out( s2 )
  );
  Mux_4x1_NBits #(
    .Bits(4)
  )
  Mux_4x1_NBits_i21 (
    .sel( s24 ),
    .in_0( D3_temp ),
    .in_1( s30 ),
    .in_2( 4'b0 ),
    .in_3( s31 ),
    .out( s3 )
  );
  Mux_4x1_NBits #(
    .Bits(4)
  )
  Mux_4x1_NBits_i22 (
    .sel( s24 ),
    .in_0( D4_temp ),
    .in_1( s32 ),
    .in_2( 4'b0 ),
    .in_3( s33 ),
    .out( s4 )
  );
  Mux_4x1_NBits #(
    .Bits(4)
  )
  Mux_4x1_NBits_i23 (
    .sel( s24 ),
    .in_0( D5_temp ),
    .in_1( s34 ),
    .in_2( 4'b0 ),
    .in_3( s35 ),
    .out( s5 )
  );
  Mux_4x1_NBits #(
    .Bits(4)
  )
  Mux_4x1_NBits_i24 (
    .sel( s24 ),
    .in_0( D6_temp ),
    .in_1( s37 ),
    .in_2( 4'b0 ),
    .in_3( s38 ),
    .out( s6 )
  );
  Mux_4x1_NBits #(
    .Bits(4)
  )
  Mux_4x1_NBits_i25 (
    .sel( s24 ),
    .in_0( D7_temp ),
    .in_1( s41 ),
    .in_2( 4'b0 ),
    .in_3( s42 ),
    .out( s21 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i26 (
    .sel( s44 ),
    .in_0( D0_temp ),
    .in_1( 4'b0 ),
    .out( s26 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i27 (
    .sel( s44 ),
    .in_0( D1_temp ),
    .in_1( 4'b0 ),
    .out( s28 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i28 (
    .sel( s44 ),
    .in_0( D2_temp ),
    .in_1( 4'b0 ),
    .out( s30 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i29 (
    .sel( s44 ),
    .in_0( D3_temp ),
    .in_1( 4'b0 ),
    .out( s32 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i30 (
    .sel( s44 ),
    .in_0( D4_temp ),
    .in_1( 4'b0 ),
    .out( s34 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i31 (
    .sel( s44 ),
    .in_0( D5_temp ),
    .in_1( 4'b0 ),
    .out( s37 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i32 (
    .sel( s44 ),
    .in_0( D6_temp ),
    .in_1( 4'b0 ),
    .out( s41 )
  );
  bcd_adder bcd_adder_i33 (
    .NumberA( D0_temp ),
    .NumberB( s8 ),
    .syc( s45 ),
    .cin( 1'b0 ),
    .N1( s25 ),
    .coutt( s46 ),
    .N2( s47 )
  );
  bcd_adder bcd_adder_i34 (
    .NumberA( D1_temp ),
    .NumberB( s10 ),
    .syc( s45 ),
    .cin( s46 ),
    .N1( s27 ),
    .coutt( s48 ),
    .N2( s49 )
  );
  bcd_adder bcd_adder_i35 (
    .NumberA( D2_temp ),
    .NumberB( s12 ),
    .syc( s45 ),
    .cin( s48 ),
    .N1( s29 ),
    .coutt( s50 ),
    .N2( s51 )
  );
  bcd_adder bcd_adder_i36 (
    .NumberA( D3_temp ),
    .NumberB( s14 ),
    .syc( s45 ),
    .cin( s50 ),
    .N1( s31 ),
    .coutt( s52 ),
    .N2( s53 )
  );
  bcd_adder bcd_adder_i37 (
    .NumberA( D4_temp ),
    .NumberB( s16 ),
    .syc( s45 ),
    .cin( s52 ),
    .N1( s33 ),
    .coutt( s54 ),
    .N2( s55 )
  );
  bcd_adder bcd_adder_i38 (
    .NumberA( D5_temp ),
    .NumberB( s18 ),
    .syc( s45 ),
    .cin( s54 ),
    .N1( s35 ),
    .coutt( s56 ),
    .N2( s57 )
  );
  bcd_adder bcd_adder_i39 (
    .NumberA( D6_temp ),
    .NumberB( s20 ),
    .syc( s45 ),
    .cin( s56 ),
    .N1( s38 ),
    .coutt( s58 ),
    .N2( s59 )
  );
  bcd_adder bcd_adder_i40 (
    .NumberA( D7_temp ),
    .NumberB( s23 ),
    .syc( s45 ),
    .cin( s58 ),
    .N1( s42 ),
    .N2( s60 )
  );
  Mux_4x1_NBits #(
    .Bits(4)
  )
  Mux_4x1_NBits_i41 (
    .sel( s24 ),
    .in_0( s47 ),
    .in_1( s47 ),
    .in_2( 4'b0 ),
    .in_3( s47 ),
    .out( s7 )
  );
  Mux_4x1_NBits #(
    .Bits(4)
  )
  Mux_4x1_NBits_i42 (
    .sel( s24 ),
    .in_0( s49 ),
    .in_1( s49 ),
    .in_2( 4'b0 ),
    .in_3( s49 ),
    .out( s9 )
  );
  Mux_4x1_NBits #(
    .Bits(4)
  )
  Mux_4x1_NBits_i43 (
    .sel( s24 ),
    .in_0( s51 ),
    .in_1( s51 ),
    .in_2( 4'b0 ),
    .in_3( s51 ),
    .out( s11 )
  );
  Mux_4x1_NBits #(
    .Bits(4)
  )
  Mux_4x1_NBits_i44 (
    .sel( s24 ),
    .in_0( s53 ),
    .in_1( s53 ),
    .in_2( 4'b0 ),
    .in_3( s53 ),
    .out( s13 )
  );
  Mux_4x1_NBits #(
    .Bits(4)
  )
  Mux_4x1_NBits_i45 (
    .sel( s24 ),
    .in_0( s55 ),
    .in_1( s55 ),
    .in_2( 4'b0 ),
    .in_3( s55 ),
    .out( s15 )
  );
  Mux_4x1_NBits #(
    .Bits(4)
  )
  Mux_4x1_NBits_i46 (
    .sel( s24 ),
    .in_0( s57 ),
    .in_1( s57 ),
    .in_2( 4'b0 ),
    .in_3( s57 ),
    .out( s17 )
  );
  Mux_4x1_NBits #(
    .Bits(4)
  )
  Mux_4x1_NBits_i47 (
    .sel( s24 ),
    .in_0( s59 ),
    .in_1( s59 ),
    .in_2( 4'b0 ),
    .in_3( s59 ),
    .out( s19 )
  );
  Mux_4x1_NBits #(
    .Bits(4)
  )
  Mux_4x1_NBits_i48 (
    .sel( s24 ),
    .in_0( s60 ),
    .in_1( s60 ),
    .in_2( 4'b0 ),
    .in_3( s60 ),
    .out( s22 )
  );
  assign D0 = D0_temp;
  assign D1 = D1_temp;
  assign D2 = D2_temp;
  assign D3 = D3_temp;
  assign D4 = D4_temp;
  assign D5 = D5_temp;
  assign D6 = D6_temp;
  assign D7 = D7_temp;
endmodule
